### ISSUE TITLE
Allow attributes to make format preserving print piece of cake

### ISSUE THREAD

**Issue by TomasVotruba** [phpstan/phpdoc-parser#11]
It probably out of scope of PHPStan (for now), but as we talked, it would be great if this package allowed *format preserving print*.

I already asked [nikic](https://github.com/nikic/PHP-Parser/issues/487) how to do it, he explained me the basics. Basically, `AbstractNode` class with set/get attributes is the first step towards it: https://github.com/nikic/PHP-Parser/commit/4d2a4d02b08b75d00067f8bf8b3c58a993abc0d0#diff-ee2208021c6e96ff1de44281aa029630R108

After few weeks I managed to make [working prototype](https://github.com/Symplify/Symplify/tree/master/packages/BetterPhpDocParser#better-phpdoc-parser), but it contains lot of boiler plate code and external storage of tokens positions etc., to make it work.

Having this would also make it easy to configure FQN namespaces, the same way [php-parser does](https://github.com/nikic/PHP-Parser/blob/3193f7aae7b6aaa1432081bf3832b01b5da0373d/lib/PhpParser/NodeVisitor/NameResolver.php#L185), without modifing the output. And other SOLID features :)

**Comment by ondrejmirtes** [comment]
Please join forces with @dantleech in #10 - he wrote in two hours ago 😊

**Comment by TomasVotruba** [comment]
I've read it, but Tokens (array, chars) and Nodes (right objects) are different thing

**Comment by dantleech** [comment]
Quite funny, I was just looking at your packages @TomasVotruba  :) My approach for format preserving was to leave the AST read-only, but instead export it to a mutable format, e.g. XML. In the XML document the nodes are represented as elements, and the tokens have node values, e.g.

```
<PhpDocNode>
  <PhpDocTextNode text="Short description"/>
  <PhpDocTextNode text=""/>
  <PhpDocTextNode text="This is a multi-line description"/>
  <PhpDocTextNode text="of the docblock."/>
  <PhpDocTextNode text=""/>
  <PhpDocTagNode name="@param">
    <ParamTagNode isVariadic="" parameterName="$bar" description="">
      <IdentifierTypeNode name="Fobar"/>
    </ParamTagNode>
  </PhpDocTagNode>
  <PhpDocTagNode name="@param">
    <ParamTagNode isVariadic="" parameterName="$foo" description="">
      <IdentifierTypeNode name="Bar\Foo"/>
    </ParamTagNode>
  </PhpDocTagNode>
  <PhpDocTagNode name="@param">
    <ParamTagNode isVariadic="" parameterName="$baz" description="">
      <IdentifierTypeNode name="int"/>
    </ParamTagNode>
  </PhpDocTagNode>
  <PhpDocTextNode text=""/>
  <PhpDocTagNode name="@throws">
    <ThrowsTagNode description="">
      <IdentifierTypeNode name="Barbar"/>
    </ThrowsTagNode>
  </PhpDocTagNode>
  <PhpDocTagNode name="@method">
    <MethodTagNode isStatic="" methodName="foobar" description="">
      <IdentifierTypeNode name="string"/>
    </MethodTagNode>
  </PhpDocTagNode>
  <PhpDocTextNode text=""/>
  <PhpDocTagNode name="@return">
    <ReturnTagNode description="">
      <IdentifierTypeNode name="Hello"/>
    </ReturnTagNode>
  </PhpDocTagNode>
</PhpDocNode>
```

Tokens would could look like `<Token type="IDENTIFIER">Fully\Qualfiied\Name</token>` and would be children of the nodes above. The text value of the document would be docblock with it's format preserved.

That's what I'm working on anyway -- the nice thing is that you can import that XML into an XML of the PHP AST, and modify the whole source tree in one place.
