### ISSUE TITLE
Question: max 120 chars for annototations | multi line annotations possible?

### ISSUE THREAD

**Issue by flobee** [phpstan/phpdoc-parser#116]
I've seen this discussion https://github.com/phpstan/phpdoc-parser/issues/6

is there alread a solution for multiline annotations e.g. for `@return` or `@var`, `@param` annotations?

i',m starting to reach the max line usage when the coding style sniffer is running.

eg.: 

```
    * @return array<string, Common_Item_Interface[]|Common_Item_List_Interface[]|Common_Item_Type_Interface[]> Associative
    * list of domains as keys and lists of IDs/items implementing Common_Item_Interface
    ...
```

**Comment by ondrejmirtes** [comment]
Multiline union types are already supported (but may require parentheses around the type): https://phpstan.org/r/90a76966-5668-47b2-82b8-71f2bade54da
