### ISSUE TITLE
Undefined property: PHPStan\PhpDocParser\Ast\Type\OffsetAccessTypeNode::$name

### ISSUE THREAD

**Issue by yannickl88** [phpstan/phpdoc-parser#121]
Hey,

We are having some issues with phpcs due to a recent change when upgrading from phpstan/phpdoc-parser 1.4.5 to 1.5.1. When running PHPCS we get the following error.

```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Undefined property:
   |       | PHPStan\PhpDocParser\Ast\Type\OffsetAccessTypeNode::$name
   |       | in
   |       | /.../vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php
   |       | on line [32](...#L32)8 (Internal.Exception)
```

I havn't done too much exploring what fails here, but this class was introduced very recently. Commit: https://github.com/phpstan/phpdoc-parser/commit/28cb38bd06f50f760a7d0d56a0de58a7b3170798

But my guess is that something fails because of this. I can see if I can reproducer this if requesed.

**Comment by yannickl88** [comment]
After some digging, https://github.com/slevomat/coding-standard/blob/master/SlevomatCodingStandard/Helpers/AnnotationTypeHelper.php#L324-L329 expects a `$name` which this node does not have.

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/releases/tag/7.2.0

**Comment by yannickl88** [comment]
thanks for the update, this solved the issues indeed.
