### ISSUE TITLE
Type parsing when combinding nullable and consts-types

### ISSUE THREAD

**Issue by puggan** [phpstan/phpdoc-parser#124]
# Bug report

Using nullable `?` on Consts-types isn't parsed as expected

### Code snippet that reproduces the problem

https://phpstan.org/r/d9e3f9e8-eca3-4380-8dda-ecf015d6a322

![image](https://user-images.githubusercontent.com/866668/169068570-44b65fbe-a7e2-421d-b67e-46bf8a95b557.png)

### Expected output

No error, expected type `?Currency::CURRENCY_*` and `null|Currency::CURRENCY_*` to be equal.

### Did PHPStan help you today? Did it make you happy in any way?

Happy as in "Yes, catched that before commitin/pushing/deploying it"

**Comment by ondrejmirtes** [comment]
Released in https://github.com/phpstan/phpstan/releases/tag/1.7.12.
