### ISSUE TITLE
request for clarification re: return types for generators

### ISSUE THREAD

**Issue by SignpostMarv** [phpstan/phpdoc-parser#13]
What's the appropriate docblock here?
```php
function Foo() : Generator {
    yield from [
        ['foo', 123, ['foo' => ['bar', 'baz', null]]],
        ['bar', 456, ['foo' => ['bar', 'baz', null]]],
        ['baz', 789, ['foo' => ['bar', 'baz', null]]],
    ];
}
```

**Comment by JanTvrdik** [comment]
Depends on what you deem to be appropriate. All of the following should work.

* `@return iterable`
* `@return Iterator`
* `@return Generator`
* `@return iterable<int, array>`
* `@return Iterator & iterable<int, array>`
* `@return Generator & iterable<int, array>`
* `@return iterable<int, array<int, mixed>>`
* `@return Iterator & iterable<int, array<int, mixed>>`
* `@return Generator & iterable<int, array<int, mixed>>`

**Comment by SignpostMarv** [comment]
I was trying to do things like `@return Generator<mixed[]>`

**Comment by JanTvrdik** [comment]
This is currently intentionally unsupported. There is no obvious way that should work, so in order to make it work a consensus (ideally formally standardized consensus) would need to be reached.

**Comment by SignpostMarv** [comment]
is re-purposing `@throws` too much of a stretch ?

**Comment by JanTvrdik** [comment]
I'm sorry, I don't understand how `@throws` could be used here in any meaningful way. Could you provide an example of what you had in mind?

**Comment by SignpostMarv** [comment]
```php
/**
* @throws RuntimeException
*/
function Foo() : Generator {
    $inner = (function() : Generator {
        yield from [1,2,3];
    })();

    $inner->throw(new RuntimeException('foo'));

    return $inner; 
}
```

**Comment by SignpostMarv** [comment]
The reason I'm thinking it'd be a bit of a stretch is `@throws` is supposed to be a hint that "calling this method will throw an exception of this type in some circumstance", whereas here it'll be the `Generator` doing the throwing if the `Generator` is looped more than 3 times.

**Comment by SignpostMarv** [comment]
@JanTvrdik I've given it some further thought; expand the scope of `@method` to be allowed to be used on methods that return Generator ?

i.e.

```php
/**
* @method int key()
* @method array<int, string|int|array<string, array<int, string|null>>> current()
* @method mixed send(array<int, string|int|array<string, array<int, string|null>>> $value)
* @method bool getReturn()
* @method mixed throw(Throwable $exception)
*/
function Foo() : Generator {
    yield from [
        ['foo', 123, ['foo' => ['bar', 'baz', null]]],
        ['bar', 456, ['foo' => ['bar', 'baz', null]]],
        ['baz', 789, ['foo' => ['bar', 'baz', null]]],
    ];

    return true;
}
```

**Comment by JanTvrdik** [comment]
@SignpostMarv No, that does not work. You need to be able to declare the generator type in all places, where type can be, e.g. it must be possible to document a parameter which accept specific type of `Generator`.

**Comment by SignpostMarv** [comment]
@JanTvrdik since Generator is a "final" class, so there aren't (currently) any more specific types of Generator, meaning we can't do this:

```php
/**
* @method int key()
* @method array<int, string|int|array<string, array<int, string|null>>> current()
* @method mixed send(array<int, string|int|array<string, array<int, string|null>>> $value)
* @method bool getReturn()
* @method mixed throw(Throwable $exception)
*/
class Bar extends Generator
{
}

/**
* @return Bar
*/
function Foo() : Generator {
    yield from [
        ['foo', 123, ['foo' => ['bar', 'baz', null]]],
        ['bar', 456, ['foo' => ['bar', 'baz', null]]],
        ['baz', 789, ['foo' => ['bar', 'baz', null]]],
    ];

    return true;
}
```

*However*, the following seems to pass psalm:^1.1 & phpstan:^0.9.2, whilst php-cs-fixer only complains about the `phpdoc_to_comment` rule:

```php
namespace Test;

use Generator;
/**
* @method int key()
* @method array<int, string|int|array<string, array<int, string|null>>> current()
* @method mixed send(array<int, string|int|array<string, array<int, string|null>>> $value)
* @method bool getReturn()
* @method mixed throw(\Throwable $exception)
*/
use Generator as Foo;

function Bar() : Foo
{
    yield from [
        ['foo', 123, ['foo' => ['bar', 'baz', null]]],
        ['bar', 456, ['foo' => ['bar', 'baz', null]]],
        ['baz', 789, ['foo' => ['bar', 'baz', null]]],
    ];

    return true;
}

public function Baz() : Generator
{
    yield from [
        ['foo', 123, ['foo' => ['bar', 'baz', null]]],
        ['bar', 456, ['foo' => ['bar', 'baz', null]]],
        ['baz', 789, ['foo' => ['bar', 'baz', null]]],
    ];

    return true;
}
```

**Comment by JanTvrdik** [comment]
@SignpostMarv You're attempting to find a creative solution for a problem that already has a industry-wide trusted solution – generics. I would strongly advice against solving this problem with any other means.
