### ISSUE TITLE
Version 1.6 removes endlines 

### ISSUE THREAD

**Issue by TomasVotruba** [phpstan/phpdoc-parser#132]
Our CI started to crash with removed endlines:
https://github.com/symplify/symplify/pull/4148/commits/36230195b068dffdc0c269e12fc094f45d176963

Any ideas what is causing it and how to fix it?

**Comment by ondrejmirtes** [comment]
Looks like `PhpDocNode::__toString()` doesn't return the same values as before, or something like that...

**Comment by rvanvelzen** [comment]
How can I reproduce this failure?

**Comment by ondrejmirtes** [comment]
I agree, this bug report isn't really useful, we don't know what you're doing with the AST in your application :) So please provide some short snippet with the manipulation you're doing and that leads to different results between 1.5.x and 1.6.0. Thanks.

**Comment by TomasVotruba** [comment]
I'll see what I can do :). I just wanted to see the commit that could help us detect miss behavior in Rector

**Comment by ondrejmirtes** [comment]
There's not that many commits, you can bisect that :)

**Comment by TomasVotruba** [comment]
Good idea, I'll try to lock it

**Comment by TomasVotruba** [comment]
This is the first commit that breaks: https://github.com/phpstan/phpdoc-parser/commit/7c621a221778202175b5c5df3ff2bcbaea5efd59

**Comment by ondrejmirtes** [comment]
I tried to reproduce it with no luck: https://github.com/phpstan/phpdoc-parser/commit/07c49b0107f79289bd8dad07e7e733b78cb6d1bf

The test passes even on 1.5.1.

**Comment by TomasVotruba** [comment]
Probably just autoload race condition.
New PHPStan release with this package should fix it :)

For now, we've added preload.php workaround:
https://github.com/phpstan/phpdoc-parser/commit/7c621a221778202175b5c5df3ff2bcbaea5efd59#r75701518

**Comment by TomasVotruba** [comment]
It will break anyone using older Rector, as it loads PHPStan's TokenIterator, but there is nothing we can do about it now.

**Comment by ondrejmirtes** [comment]
Done: https://github.com/phpstan/phpstan/releases/tag/1.7.12

**Comment by TomasVotruba** [comment]
I'll try it, thanks :+1:

**Comment by TomasVotruba** [comment]
It works well, I'll follow with Rector release
