### ISSUE TITLE
[PSR-5] support colon in tag name

### ISSUE THREAD

**Issue by jaapio** [phpstan/phpdoc-parser#157]
To make this parser better compatible with PSR-5 I would like to add support for a colon (`:`) in the tag name. As described: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#532-tag-specialization 

These specializations a not used in the wild, but it should be a small change allowing more projects to adopt this parser. 

Please let me know if you are open of a PR to add this.

**Comment by ondrejmirtes** [comment]
Yeah, sure, no problem :)
