### ISSUE TITLE
[Suggestion] Add support for @internal tags

### ISSUE THREAD

**Issue by JacquesDurand** [phpstan/phpdoc-parser#172]
Hi !
First, thanks for all the awesome work you've been doing !

Would you be interested in adding support for `@internal` phpdoc tags ?

I think I can make a PR in the following days, I just prefered to ask beforehand in case it is already in the making (or if you'd rather not see this implemented for any reason).

**Comment by ondrejmirtes** [comment]
What is the current result for `@internal` PHPDoc tag in the parser, and what is your expectation?

**Comment by JacquesDurand** [comment]
I have not tested it thoroughly, but I believe such a tag would currently be identified as a `Ast\PhpDoc\GenericTagValueNode`. (following the switch logic in the parser)
I would propose creating an `Ast\PhpDoc\InternalTagValueNode` with a simple, possibly empty, description.

In my use case (and I understand completely if it does not match your preferences), it would allow me more easily to check if a class is declared internal by checking if its doc comment contains an instance of `InternalTagValueNode` (and then skip it in further tasks if that's the case).
 
Do you think it could have any value ?

**Comment by jaapio** [comment]
You might want to look at https://github.com/phpDocumentor/ReflectionDocBlock it supports more tags than this library. This library is purely a parser that returns an AST that needs to be interpreted. From a phpstan perspective, the InternalTag doesn't have any value. And it looks like you are looking for a more complete set of tags. 

The behavior of the internal tag is more complex than you might think upfront. As people can also use it inline in descriptions. 

https://docs.phpdoc.org/3.0/guide/references/phpdoc/inline-tags/internal.html#internal

**Comment by ondrejmirtes** [comment]
It's fine to use our phpdoc-parser for this purpose, but returning InternalTagValueNode instead of GenericTagValueNode is purely a cosmetic change. You can already find out whether the PHPDoc has `@internal` in the current release.

**Comment by JacquesDurand** [comment]
Thank you for your explanations, I indeed now get that it does not add much phpstan-wise ( and that it is in fact more complex than I thought, with the inline possibility ). I think I will indeed not have any issue finding out if a tag is `@internal` without the need of the (incomplete) cosmetic changes I proposed. 
Thanks again for your time (and sorry for wasting it), keep up the great work !
