### ISSUE TITLE
Add support for `@property $foo` syntax.

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpdoc-parser#239]
Hi @ondrejmirtes, 

Currently the parser correctly parse
```
@property mixed $foo
```
but fail on 
```
@property $foo
```
for instance https://phpstan.org/r/2534dcd1-fb4e-47af-80f2-1d2f896ec6aa

This is a syntax used by at least the following lib https://github.com/gocardless/gocardless-pro-php/blob/882efd66430b6dec9baeceb2ea6bb7078c3ef908/lib/Resources/Block.php#L14.

And I would say that since we can write 
```
@method doThings($foo)
```
or to define a property without a type
```
private $foo
```
it could make sens to allow
```
@property $foo
```

Would you open to support such syntax and allowing type to be nullable in PropertyTagValueNode ?

**Comment by ondrejmirtes** [comment]
I disagree. Libs should follow what's already supported in the world, not invent new syntax and hope for the best.

**Comment by VincentLanglet** [comment]
> I disagree. Libs should follow what's already supported in the world, not invent new syntax and hope for the best.

I understand the point of view and agree with it but I made search and I think the syntax is valid,
according to Phpdocumentor, https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.property.pkg.html

It says 
> phpDocumentor will display the optional description unmodified, and **defaults to "mixed" if the datatype is not present.**

So it seems allowed that the "datatype is not present".

**Comment by ondrejmirtes** [comment]
I don't think that something written 17 years ago is relevant here.

**Comment by VincentLanglet** [comment]
> I don't think that something written 17 years ago is relevant here.

Sure.

So I just 
- downloaded the latest phpDocumentor phar https://github.com/phpDocumentor/phpDocumentor
- Run this latest version on the following code
<img width="400" alt="image" src="https://github.com/phpstan/phpdoc-parser/assets/9052536/6f4d250f-492c-48c6-b822-e5a26969f5f5">

- And it's correctly parsed by PhpDocumentor
<img width="568" alt="image" src="https://github.com/phpstan/phpdoc-parser/assets/9052536/4e62fb15-7ae8-4360-9765-401a4a874dad">

So the syntax still seems to be a valid one in 2024.

**Comment by VincentLanglet** [comment]
The syntax is also supported by PHPStorm
<img width="611" alt="image" src="https://github.com/phpstan/phpdoc-parser/assets/9052536/f9f376be-59c1-47a3-8b55-e9fd034d76a3">

> Libs should follow what's already supported in the world, not invent new syntax and hope for the best.

My point is that it's not easy to ask a lib to change his syntax when the "only" tools (phpdocumentor/phpstorm) there are using are supporting the syntax. And it would be helpful to not having to write stubs for every classes of this lib.
I'm ok doing all the PR needed for this support.

**Comment by ondrejmirtes** [comment]
Sorry, I'm not going to add this and I'm locking this thread. phpdoc-parser has been introduced to [PHPStan 6.5 years ago](https://phpstan.org/blog/phpstan-0-9-a-huge-leap-forward) and no one up until now asked for this which means this isn't really an issue.

`@property` without a type makes the code worse. I want to make the PHP ecosysytem better not by allowing `@property` without a type, but by forcing people to add the type instead.
