### ISSUE TITLE
phpcs broken on 7.3

### ISSUE THREAD

**Issue by mglaman** [phpstan/phpdoc-parser#24]
consistence/coding-standard:~2 requires a broken code_sniffer, but we cannot bump it to a higher version due to a conflict on slevomat/coding-standard.

**Comment by mglaman** [comment]
These minimal changes got it working, but added new phpcs failures:


```
	"require-dev": {
		"consistence/coding-standard": "^3.2.0",
		"slevomat/coding-standard": "^4.6.0",
```

**Comment by ondrejmirtes** [comment]
Fixed (used settings from phpstan/phpstan): https://github.com/phpstan/phpdoc-parser/commit/a3dbd6c257ee8b2ca1af9656d8305049c4a3ebee
