### ISSUE TITLE
class-string-map<T of Foo, T>

### ISSUE THREAD

**Issue by ahjdev** [phpstan/phpdoc-parser#246]
The parser cannot detect `class-string-map<T of Foo, T>` (Which is I think found it in psalm)

**Comment by stof** [comment]
Related to https://github.com/phpstan/phpstan/issues/9521 because phpstan does not support those types at all

**Comment by ondrejmirtes** [comment]
The parser supports this type, but PHPStan does not. Therefore keeping https://github.com/phpstan/phpstan/issues/9521 open is sufficient.
