### ISSUE TITLE
@template-default T=5

### ISSUE THREAD

**Issue by ahjdev** [phpstan/phpdoc-parser#247]
The parser cannot detect `@template-default T=5` (Which is I found it in psalm)

**Comment by ondrejmirtes** [comment]
Psalm does not support this syntax. See an open issue: https://github.com/vimeo/psalm/issues/5407

This has been recently implemented this using `@template T = 5`: https://x.com/OndrejMirtes/status/1843920480342057154

**Comment by ahjdev** [comment]
Oh tnx
