### ISSUE TITLE
BUG: Too few arguments to function Lexer::__construct(), 0 passed in StringTypeResolver.php 

### ISSUE THREAD

**Issue by bh-teufels** [phpstan/phpdoc-parser#257]
Too few arguments to function PHPStan\PhpDocParser\Lexer\Lexer::__construct(), 0 passed in /app/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php on line 66 and exactly 1 expected

occurs in Version: 2.0.0

Version: 1.33.0 working

**Comment by ondrejmirtes** [comment]
This is fixed in `symfony/type-info` but not yet released. Update to this commit in their 7.1-dev branch: https://github.com/symfony/type-info/commit/51535dde21c7abf65c9d000a30bb15f6478195e6
