### ISSUE TITLE
Generic<Type>[] incorrectly failing

### ISSUE THREAD

**Issue by VincentLanglet** [phpstan/phpdoc-parser#36]
# Bug report

### Code snippet that reproduces the problem

Something like
```
Collection<int, int>[]
```
Should be a valid type

No error with psalm: https://psalm.dev/r/26d249d13d
An error with phpstan (the last one): https://phpstan.org/r/a42e2d1b-d1fe-4c8b-a4df-9c6e61b422b1

```
PHPDoc tag @param has invalid value (Collection<int, int>[] $bars): Unexpected token "[", expected variable at offset 38
```

An actual workaround is `(Collection<int, int>)[]` but I think the phpDoc parser should still be improved to handle the syntax.

**Comment by VincentLanglet** [comment]
It's the same for
```
@param array{int: int}[] $bars
```

**Comment by JanTvrdik** [comment]
This is expected. `[]` syntax has no clear meaning and should be deprecated in favor of generics.
Use `array<Collection<int, int>>` or `iterable<Collection<int, int>>` depending on what you mean.

**Comment by VincentLanglet** [comment]
I disagree. Even if you think it should be deprecated, it's not deprecated.

We have some example,
here: https://psalm.dev/docs/annotating_code/type_syntax/array_types/
```
ValueType[]
```
here: https://docs.phpdoc.org/references/phpdoc/types.html#arrays
```
(int|string)[]
```

So there should still be support for the syntax.

Someone writing **correctly** his PhpDoc should not have an error with phpstan.

**Comment by iluuu1994** [comment]
We already support this for everything else:

```
float|int[] => float | (int[])
```

https://phpstan.org/r/a98d8d62-83a8-440b-960d-e778ba4bfe27

It's a postfix, so it's closely associated with the term just before it (like it already is in the example above). Not sure what makes the presented case with `Collection` or `array{...}` any different.

**Comment by ondrejmirtes** [comment]
I'm not against it if you find a way how to implement it in the parser :)

**Comment by iluuu1994** [comment]
Should be easy, parse postfixes before operators like `|`. I don' have time today but I'll see if I can do it tomorrow. That would be one less discrepancy between Psalm and PHPStan which would be cool.

**Comment by iluuu1994** [comment]
There you go. I also noticed that the following were broken:

```php
callable(): int[]
// was parsed as callable(): int

$this[]
// was parsed as $this
```

**Comment by ondrejmirtes** [comment]
Thank you. It's gonna be released very soon.
