### ISSUE TITLE
multiline array shape not merged?

### ISSUE THREAD

**Issue by orklah** [phpstan/phpdoc-parser#38]
Hi, I have a multiline array shape in a project that doesn't seem to be parsed.

When searching for an answer, I found #33 that do exactly that.

However, as though this was supposed to be merged according to
https://github.com/phpstan/phpstan/issues/2497#issuecomment-547147463
and 
https://github.com/phpstan/phpdoc-parser/pull/33#issuecomment-546633385

The actual commit was pretty empty:
https://github.com/phpstan/phpdoc-parser/commit/18b0e92b63ada4f1dc7e30265950bd1d10f5fb75

and  I can't find the content of the PR on master.

For example: 
https://github.com/shmax/phpdoc-parser/blob/17d28cc099984a5ecbbbfb7b102daa45ce1af62f/tests/PHPStan/Parser/TypeParserTest.php#L481
https://github.com/shmax/phpdoc-parser/blob/master/tests/PHPStan/Parser/TypeParserTest.php#L481
should be the same

https://github.com/shmax/phpdoc-parser/blob/17d28cc099984a5ecbbbfb7b102daa45ce1af62f/src/Parser/TypeParser.php#L224
https://github.com/shmax/phpdoc-parser/blob/master/src/Parser/TypeParser.php#L224
too.

Was this reverted afterward?

**Comment by ondrejmirtes** [comment]
Hi, can you post an example on phpstan.org what doesn't get parsed in your case?

**Comment by orklah** [comment]
https://phpstan.org/r/5d107a04-a3ad-4415-a151-576236dddbd1

**Comment by ondrejmirtes** [comment]
It's just that you can't put the newline anywhere. This works: https://phpstan.org/r/22622ed0-2a45-40c0-bb7a-e7567be39fee

**Comment by ondrejmirtes** [comment]
Also look into the feature of type aliases (https://github.com/phpstan/phpstan/releases/tag/0.12.9), you might like it :)

**Comment by orklah** [comment]
Thanks :)

Types aliase could indeed be handy for my use-case :)
