### ISSUE TITLE
Array shape with slash in keys doesn't work

### ISSUE THREAD

**Issue by bendavies** [phpstan/phpdoc-parser#39]
# Bug report

Describe array shapes with slashes in keys does not work,

### Code snippet that reproduces the problem

https://phpstan.org/r/d02b8108-1bd0-4bbb-82be-69e90343395d

### Expected output

No errors.

**Comment by ondrejmirtes** [comment]
Moved to `phpstan/phpdoc-parser`.

**Comment by stof** [comment]
Well, according to the grammar, this seems expected, as `/` is not allowed in TokenIdentifier.

But I tried quoting the key, and it also breaks, which is unexpected as the type grammar allows ConstantString for keys.

**Comment by ondrejmirtes** [comment]
Try to debug it please when you're already in the code :) There's also a related issue: https://github.com/phpstan/phpdoc-parser/issues/40

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpdoc-parser/commit/97a0114d7f875047afdc34b3042626398178318b + https://github.com/phpstan/phpstan-src/commit/e210a6e561ff742ac0a0f381a6190c9f81dddc92

You need to use quotes around the string: https://phpstan.org/r/af633896-7467-45b5-b961-9ffa2b4951ae
