### ISSUE TITLE
Issues with array keys with $

### ISSUE THREAD

**Issue by christeredvartsen** [phpstan/phpdoc-parser#40]
# Bug report

Not completely sure if this is an issue with phpstan, or underlying libraries that parse doc-blocks, but I'll start here. If you feel this should be reported in a different repo, feel free to point me in the right direction.

### Code snippet that reproduces the problem

https://phpstan.org/r/fadf7cdd-6ab0-4a1a-b4b0-4534371c0680

### Expected output

The issue is that I can't seem to document the array key called `$ref`. I have tried to escape the `$`, but that does not seem to help.

**Comment by ondrejmirtes** [comment]
Fixed: https://github.com/phpstan/phpdoc-parser/commit/97a0114d7f875047afdc34b3042626398178318b + https://github.com/phpstan/phpstan-src/commit/e210a6e561ff742ac0a0f381a6190c9f81dddc92

You need to use quotes around the key: https://phpstan.org/r/59b18a73-e906-497b-a05f-92ffb84ad826

**Comment by ondrejmirtes** [comment]
BTW: Psalm has currently problem with `"$ref"` but I'm promised it's gonna be fixed :)
