### ISSUE TITLE
unresolvable type when starting @return description with html tag

### ISSUE THREAD

**Issue by pablotheissen** [phpstan/phpdoc-parser#41]
# Bug report
When using an html tag as the first part of the desciprtion of the `@return` statement, PHPStan returns the error `PHPDoc tag @return contains unresolvable type.`:
```
 * @return bool <b>TRUE</b> on success or <b>FALSE</b> on failure.
```
This only occurs with the characters < and & as the first char of the description. All other cases I tested worked out fine.

### Code snippet that reproduces the problem
https://phpstan.org/r/6bd09036-ee66-4fd4-9e69-6d4a5b51fb83

### Expected output
I found nothing against using html in the start of a PHPdoc description, so this snippet shouldn't return an error.

**Comment by ondrejmirtes** [comment]
Yeah, this is difficult because it conflicts with the generics syntax.

**Comment by ondrejmirtes** [comment]
Fixed by https://github.com/phpstan/phpdoc-parser/pull/47
