### ISSUE TITLE
Multi Line Generic Types are invalid

### ISSUE THREAD

**Issue by ServerExe** [phpstan/phpdoc-parser#42]
# Bug report

PhpStan-Version: 0.12.19

The following error occurs when trying to declare a multi lined Generics annotation:
```
PHPDoc tag @implements has invalid value (HelloInterface< Foo, Bar): Unexpected token "\n *", expected type at offset 34
```

### Code snippet that reproduces the problem
https://phpstan.org/r/80a149d9-5820-4041-bf3b-4b6e19de6b09

### Expected output
`No errors!` as it is in:
https://phpstan.org/r/08857dad-5e7b-4615-9c99-f3397aa204ce

**Comment by icanhazstring** [comment]
@ondrejmirtes thanks for moving. Can you point ppl in the right direction, so maybe someone can get startet right away :)

**Comment by ondrejmirtes** [comment]
See how multiline array shapes are implemented: https://github.com/phpstan/phpdoc-parser/blob/d4c4cd3caecfa40661cff48b24b6b5216c488458/src/Parser/TypeParser.php#L282-L304

This is where generic types are parsed: https://github.com/phpstan/phpdoc-parser/blob/d4c4cd3caecfa40661cff48b24b6b5216c488458/src/Parser/TypeParser.php#L165-L176

**Comment by icanhazstring** [comment]
Will try to tackle this one :)

**Comment by icanhazstring** [comment]
@ondrejmirtes would it be wise to update the `Tokenzier` to avoid tokenizing the `\n` as a token itself.
The only thing "breaking" the code right now is the "new_line" token. With this removed, everything should work fine.

**Comment by icanhazstring** [comment]
Nevermind, just found out how the parsing works exactly :)

**Comment by icanhazstring** [comment]
This can be closed then @ondrejmirtes :)

**Comment by ondrejmirtes** [comment]
Yes, implemented in https://github.com/phpstan/phpdoc-parser/pull/44 :)
