### ISSUE TITLE
Constant wildcard with `Class::*|null` or `list<Class::*>`

### ISSUE THREAD

**Issue by jderusse** [phpstan/phpdoc-parser#45]
Thanks for this new feature, but it fail to parse the constraint whenit's combined 
```
list<QueueAttributeName::*>
ParameterTier::*|null
```

**Comment by ondrejmirtes** [comment]
Fixed, thank you! It will take a few days before the next PHPStan gets released with this parser version: https://github.com/phpstan/phpdoc-parser/commit/d840b6956b47930f19eb9d8dbc9553650d5072d6

**Comment by jderusse** [comment]
Thanks a lot for the patch!

**Comment by ondrejmirtes** [comment]
Released in PHPStan 0.12.23 :)

**Comment by jderusse** [comment]
thanks
