### ISSUE TITLE
Annotation @TYPO3\CMS\Extbase\Annotation\Inject not tokenized correctly?

### ISSUE THREAD

**Issue by sabbelasichon** [phpstan/phpdoc-parser#59]
Currently i have the problem that all annotations prefixed with `@TYPO3` are not tokenized correctly by the Lexer class. The end result of the tag variable is always `@TYPO.` The rest is cut off.
I guess the failure is located here https://github.com/phpstan/phpdoc-parser/blob/master/src/Lexer/Lexer.php#L144 because numbers are not allowed. 
I am not really sure how i can test it or prove it. If you could guide me i would be happy to fix this, if it is considered a bug

**Comment by JanTvrdik** [comment]
I guess we could change the pattern to `@[a-z-][a-z0-9-]*+`

**Comment by sabbelasichon** [comment]
@JanTvrdik Should i open a PR for that?
