### ISSUE TITLE
Update .gitattributes

### ISSUE THREAD

**Issue by williamdes** [phpstan/phpdoc-parser#71]
https://github.com/phpstan/phpdoc-parser/blob/e352d065af1ae9b41c12d1dfd309e90f7b1f55c9/.gitattributes#L3

To be added:
- `.editorconfig`
- `.github`
- `build-abnfgen.sh`
- `build.xml`
- `phpstan.neon`
- `phpcs.xml`
- `build-cs`

Maybe also: `doc/grammars`

To be removed:
- `.travis.yml`

**Comment by ondrejmirtes** [comment]
Feel free to send a PR. Closing as I don't consider this a bug, but it's a perfect contribution opportunity :)
